version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: db_app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  
  db_test:
    image: postgres:16-alpine
    container_name: db_test_app
    env_file:
      - .env
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_app
    env_file:
      - .env
    ports:
      - 82:80

  redis:
    image: redis:7-alpine
    container_name: redis_app
  
  app:
    build:
      context: .
    container_name: fastapi_app
    env_file:
      - .env
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: .
    container_name: celery_app
    env_file:
      - .env
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: flower_app
    env_file:
      - .env
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555

volumes:
    postgres_data:


# version: "3.7"
# services:
#   db:
#     image: postgres:15
#     container_name: db_app
#     env_file:
#       - .env

#   redis:
#     image: redis:7
#     container_name: redis_app
  
#   app:
#     build:
#       context: .
#     container_name: fastapi_app
#     env_file:
#       - .env
#     command: ["/fastapi_app/docker/app.sh"]
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#       - redis

#   celery:
#     build:
#       context: .
#     container_name: celery_app
#     env_file:
#       - .env
#     command: ["/fastapi_app/docker/celery.sh", "celery"]
#     depends_on:
#       - redis

#   flower:
#     build:
#       context: .
#     container_name: flower_app
#     env_file:
#       - .env
#     command: ["/fastapi_app/docker/celery.sh", "flower"]
#     depends_on:
#       - redis
#       - celery
#     ports:
#       - 5555:5555


# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     env_file:
#       - .env

#   redis:
#     image: redis:7

#   app:
#     build:
#       context: .
#     env_file:
#       - .env
#     command: ["/fastapi_app/docker/app.sh"]
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#       - redis

#   celery:
#     build:
#       context: .
#     env_file:
#       - .env
#     command: ["/fastapi_app/docker/celery.sh", "celery"]
#     depends_on:
#       - redis

#   flower:
#     build:
#       context: .
#     env_file:
#       - .env
#     command: ["/fastapi_app/docker/celery.sh", "flower"]
#     ports:
#       - 5555:5555
#     depends_on:
#       - redis
#       - celery


# version: '3.8'

# services:
#    db:
#     image: postgres:16-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file: .env
  
#   redis:
#     image: redis:7.2.3-alpine

#   app:
#     build: .
#     command: gunicorn src.main:app --host 0.0.0.0 --port 8000
#     ports:
#       - 8000:8000
#     env_file: .env
#     depends_on:
#       - db
#       - redis

  # celery:
  #   build:
  #     context: .
  #   env_file:
  #     - .env
  #   command: ["/app/docker/celery.sh", "celery"]
  #   depends_on:
  #     - redis

  # flower:
  #   build:
  #     context: .
  #   env_file:
  #     - .env
  #   command: ["/app/docker/celery.sh", "flower"]
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - redis
  #     - celery

# volumes:
#     postgres_data:
