version: '3.8'

services:
  app:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file: .env
  
  redis:
    image: redis:7.2.3-alpine

volumes:
    postgres_data: